### ISSUE TITLE
[BUG] filter_convolve is not compatible with latest scipy

### ISSUE THREAD

**Issue by chaithyagr** [CEA-COSMIC/ModOpt#77]
With recent scipy release in December 2019, the filter convolve seems to be having issues:

```python
>>> from modopt.signal.wavelet import get_mr_filters, filter_convolve
>>> import numpy as np
>>> T = get_mr_filters((512,512),['-t24','-n4'],coarse=True)
>>> A = filter_convolve(np.zeros((512,512)), T)
```
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/volatile/Chaithya/Codes/ModOpt/modopt/signal/wavelet.py", line 284, in filter_convolve
    return np.array([convolve(data, f, method=method) for f in filters])
  File "/volatile/Chaithya/Codes/ModOpt/modopt/signal/wavelet.py", line 284, in <listcomp>
    return np.array([convolve(data, f, method=method) for f in filters])
  File "/volatile/Chaithya/Codes/ModOpt/modopt/math/convolve.py", line 101, in convolve
    return scipy.signal.fftconvolve(data, kernel, mode='same')
  File "/neurospin/optimed/Chaithya/Environments/maniac_gpu/lib/python3.5/site-packages/scipy/signal/signaltools.py", line 542, in fftconvolve
    ret = _freq_domain_conv(in1, in2, axes, shape, calc_fast_len=True)
  File "/neurospin/optimed/Chaithya/Environments/maniac_gpu/lib/python3.5/site-packages/scipy/signal/signaltools.py", line 383, in _freq_domain_conv
    sp2 = fft(in2, fshape, axes=axes)
  File "/neurospin/optimed/Chaithya/Environments/maniac_gpu/lib/python3.5/site-packages/scipy/fft/_backend.py", line 23, in __ua_function__
    return fn(*args, **kwargs)
  File "/neurospin/optimed/Chaithya/Environments/maniac_gpu/lib/python3.5/site-packages/scipy/fft/_pocketfft/basic.py", line 186, in r2cn
    return pfft.r2c(tmp, axes, forward, norm, None, workers)
RuntimeError: unsupported data type
```

**Are you planning to submit a Pull Request?**
- [ ] Yes
- [X] No

**Comment by sfarrens** [comment]
@chaithyagr I have opened a PR (#93) to resolve this issue. I have tested your example with the latest version of Scipy (1.4.1) and it works.
